### ISSUE TITLE
Support for nested sealed classes?

### ISSUE THREAD

**Issue by ursusursus** [ZacSweers/MoshiX#117]
Hi, I'm trying to migrate to moshi.sealed but this I'm not sure if is supported

```kotlin
@JsonClass(generateAdapter = true, generator = "sealed:type")
    sealed class Status {
        sealed class HasBonus : Status() {
            abstract val bonus: Double

            @TypeLabel("active")
            @JsonClass(generateAdapter = true)
            data class Active(override val bonus: Double) : HasBonus()

            @TypeLabel("eligible")
            @JsonClass(generateAdapter = true)
            data class Eligible(val id: String, override val bonus: Double) : HasBonus()

            @TypeLabel("missing_consumer")
            @JsonClass(generateAdapter = true)
            data class MissingConsumer(override val bonus: Double) : HasBonus()

            @TypeLabel("missing_contributor")
            @JsonClass(generateAdapter = true)
            data class MissingContributor(override val bonus: Double) : HasBonus()
        }

        @DefaultObject
        @TypeLabel("not_eligible")
        object NotEligible : Status()
    }
```
```
error: Missing @TypeLabel.
        public static abstract class HasBonus extends sk.o2.mojeo2.mcc.data.Mcc.Status {
                               ^
```
i.e. nested sealed classes

**Comment by ursusursus** [comment]
If I just put the TypeLabel there, it compile, but the generated code is wrong 

```
@Suppress("UNCHECKED_CAST")
  private val runtimeAdapter: JsonAdapter<Mcc.Status> =
      PolymorphicJsonAdapterFactory.of(Mcc.Status::class.java, "type")
        .withSubtype(Mcc.Status.HasBonus::class.java, "has-bonus")
        .withDefaultValue(Mcc.Status.NotEligible)
        .create(Mcc.Status::class.java, emptySet(), moshi) as JsonAdapter<Mcc.Status>
```

**Comment by ZacSweers** [comment]
What's wrong with the generated code in your second comment?

**Comment by ursusursus** [comment]
Oh, you mean that there is another Polymorphic factory generate just for the HasBonus hierarchy?

**Comment by ZacSweers** [comment]
Yeah, it needs both a type label and a JsonClass annotation (or custom adapter handling it elsewhere)

**Comment by ursusursus** [comment]
Hmm, it doesn't seem to work at runtime 

```
@JsonClass(generateAdapter = true, generator = "sealed:type")
    sealed class Status {
        @TypeLabel("has_bonus")
        @JsonClass(generateAdapter = true, generator = "sealed:bonus_type")
        sealed class HasBonus : Status() {
            abstract val bonus: Double

            @TypeLabel("active")
            @JsonClass(generateAdapter = true)
            data class Active(override val bonus: Double) : HasBonus()

            @TypeLabel("eligible")
            @JsonClass(generateAdapter = true)
            data class Eligible(val id: String, override val bonus: Double) : HasBonus()

            @TypeLabel("missing_consumer")
            @JsonClass(generateAdapter = true)
            data class MissingConsumer(override val bonus: Double) : HasBonus()

            @TypeLabel("missing_contributor")
            @JsonClass(generateAdapter = true)
            data class MissingContributor(override val bonus: Double) : HasBonus()
        }

        @TypeLabel("not_eligible")
        object NotEligible : Status()
    }
```

```
 java.lang.IllegalArgumentException: Expected one of [class sk.o2.mojeo2.mcc.data.Mcc$Status$HasBonus, class sk.o2.mojeo2.mcc.data.Mcc$Status$NotEligible] but found Eligible(id=ID:SOME:PRODUCT, bonus=20.0), a class sk.o2.mojeo2.mcc.data.Mcc$Status$HasBonus$Eligible. Register this subtype.
        at com.squareup.moshi.adapters.PolymorphicJsonAdapterFactory$PolymorphicJsonAdapter.toJson(PolymorphicJsonAdapterFactory.java:307)
        at com.squareup.moshi.internal.NullSafeJsonAdapter.toJson(NullSafeJsonAdapter.java:50)
        at sk.o2.mojeo2.mcc.data.Mcc_StatusJsonAdapter.toJson(Mcc_StatusJsonAdapter.kt:33)
        at sk.o2.mojeo2.mcc.data.Mcc_StatusJsonAdapter.toJson(Mcc_StatusJsonAdapter.kt:15)
        at com.squareup.moshi.internal.NullSafeJsonAdapter.toJson(NullSafeJsonAdapter.java:50)
        at com.squareup.moshi.JsonAdapter.toJson(JsonAdapter.java:82)
        at com.squareup.moshi.JsonAdapter.toJson(JsonAdapter.java:90)
        at sk.o2.sqldelight.JsonColumnAdapter.encode(JsonColumnAdapter.kt:29)
        at sk.o2.sqldelight.JsonColumnAdapter.encode(JsonColumnAdapter.kt:21)
```

JsonColumnAdapter is just forwarding to moshi
```
class JsonColumnAdapter<T : Any>(moshi: Moshi, type: KType) : ColumnAdapter<T, String> {
    private val jsonAdapter = moshi.adapter<T>(type)

    override fun decode(databaseValue: String): T {
        return jsonAdapter.fromJson(databaseValue)!!
    }

    override fun encode(value: T): String {
        return jsonAdapter.toJson(value)
    }
}
```

so what I'm trying to serialize is
`Status.HasBonus.Eligible(id=ID:SOME:PRODUCT, bonus=20.0)`

**Comment by ZacSweers** [comment]
sidenote - please use syntax highlighting in your code snippets to make them more readable, speeds things up a lot.

For the issue - I'm not sure what the right approach is here. PolymorphicJsonAdapterFactory doesn't seem to really play well with encoding subtypes of its known subtypes. I don't think this works in standard Moshi either. Could you file a feature request over there for better supporting encoding subtypes of known polymorphic types? I don't really know if/how it would look off-hand
