### ISSUE TITLE
Moshi-KSP generic typealias fails to compile

### ISSUE THREAD

**Issue by angusholder** [ZacSweers/MoshiX#127]
```kotlin
package com.example

import com.squareup.moshi.JsonClass

enum class Animal {
    Cat,
    Dog,
}

typealias AnimalMap<T> = Map<Animal, T>

@JsonClass(generateAdapter = true)
data class ApiResponse(
    val animalNames: AnimalMap<String>,
)
```

fails with the error

<details>
<summary>java.lang.IllegalStateException: No type argument found for T! Anaylzing co.mopo.android.data.http.ApiResponse</summary>

```
e: [ksp] java.lang.IllegalStateException: No type argument found for T! Anaylzing co.mopo.android.data.http.ApiResponse
	at dev.zacsweers.moshix.ksp.KotlinPoetSpKt$toTypeParameterResolver$typeParamResolver$1.invoke(KotlinPoetSp.kt:81)
	at dev.zacsweers.moshix.ksp.KotlinPoetSpKt$toTypeParameterResolver$typeParamResolver$1.invoke(KotlinPoetSp.kt:78)
	at dev.zacsweers.moshix.ksp.KotlinPoetSpKt$toTypeParameterResolver$resolver$1.get(KotlinPoetSp.kt:87)
	at dev.zacsweers.moshix.ksp.KotlinPoetSpKt.toTypeName(KotlinPoetSp.kt:51)
	at dev.zacsweers.moshix.ksp.KotlinPoetSpKt.toTypeName(KotlinPoetSp.kt:134)
	at dev.zacsweers.moshix.ksp.KotlinPoetSpKt.toTypeName(KotlinPoetSp.kt:50)
	at dev.zacsweers.moshix.ksp.KotlinPoetSpKt.toTypeName(KotlinPoetSp.kt:52)
	at dev.zacsweers.moshix.ksp.KotlinPoetSpKt.toTypeName(KotlinPoetSp.kt:145)
	at dev.zacsweers.moshix.ksp.TargetTypesKt.primaryConstructor(TargetTypes.kt:161)
	at dev.zacsweers.moshix.ksp.TargetTypesKt.targetType(TargetTypes.kt:80)
	at dev.zacsweers.moshix.ksp.JsonClassSymbolProcessor.adapterGenerator(JsonClassSymbolProcessorProvider.kt:167)
	at dev.zacsweers.moshix.ksp.JsonClassSymbolProcessor.process(JsonClassSymbolProcessorProvider.kt:119)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension$doAnalysis$4$1.invoke(KotlinSymbolProcessingExtension.kt:172)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension$doAnalysis$4$1.invoke(KotlinSymbolProcessingExtension.kt:171)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension.handleException(KotlinSymbolProcessingExtension.kt:249)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension.doAnalysis(KotlinSymbolProcessingExtension.kt:171)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration(TopDownAnalyzerFacadeForJVM.kt:119)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration$default(TopDownAnalyzerFacadeForJVM.kt:85)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:514)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:505)
	at org.jetbrains.kotlin.cli.common.messages.AnalyzerWithCompilerReport.analyzeAndReport(AnalyzerWithCompilerReport.kt:112)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.analyze(KotlinToJVMBytecodeCompiler.kt:505)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:189)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli$default(KotlinToJVMBytecodeCompiler.kt:155)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:169)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:52)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:88)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:44)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:98)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1575)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:359)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:562)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:796)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:677)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:676)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

</details>

Great work on this by the way, I've seen a nice improvement to my compile time!

**Comment by ZacSweers** [comment]
Thanks for the repro case, I'll take a look. Apologies for missing this in the last release, it slipped my mind
