### ISSUE TITLE
moshi-ir generated JsonAdapter crashes when trying to resolve classes with kotlin-reflect on the classpath

### ISSUE THREAD

**Issue by gabrielittner** [ZacSweers/MoshiX#202]
After switching from kapt to moshi-ir we're seeing this crash:
```
    kotlin.reflect.jvm.internal.KotlinReflectionInternalError: Unresolved class: int
        at kotlin.reflect.jvm.internal.KClassImpl.reportUnresolvedClass(KClassImpl.kt:328)
        at kotlin.reflect.jvm.internal.KClassImpl.access$reportUnresolvedClass(KClassImpl.kt:44)
        at kotlin.reflect.jvm.internal.KClassImpl$Data$descriptor$2.invoke(KClassImpl.kt:56)
        at kotlin.reflect.jvm.internal.KClassImpl$Data$descriptor$2.invoke(KClassImpl.kt:48)
        at kotlin.reflect.jvm.internal.ReflectProperties$LazySoftVal.invoke(ReflectProperties.java:93)
        at kotlin.reflect.jvm.internal.ReflectProperties$Val.getValue(ReflectProperties.java:32)
        at kotlin.reflect.jvm.internal.KClassImpl$Data.getDescriptor(KClassImpl.kt:48)
        at kotlin.reflect.jvm.internal.KClassImpl.getDescriptor(KClassImpl.kt:182)
        at kotlin.reflect.jvm.internal.KClassImpl.getDescriptor(KClassImpl.kt:44)
        at kotlin.reflect.full.KClassifiers.createType(KClassifiers.kt:48)
        at kotlin.reflect.jvm.internal.ReflectionFactoryImpl.typeOf(ReflectionFactoryImpl.java:124)
        at kotlin.jvm.internal.Reflection.typeOf(Reflection.java:127)
        at com.freeletics.domain.loggedinuser.RefreshTokenJsonAdapter.<init>(Unknown Source:26)
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at com.squareup.moshi.internal.Util.generatedAdapter(Util.java:588)
        at com.squareup.moshi.StandardJsonAdapters$1.create(StandardJsonAdapters.java:61)
```

The crash only seems to happen when `kotlin-reflect` is on the runtime classpath.

Decompiled code generated with kapt
```
moshi.adapter((Type)(Class<String>)String.class,·SetsKt.emptySet(),·"email");
moshi.adapter((Type)(Class<ProfilePicture>)ProfilePicture.class,·SetsKt.emptySet(),·"profilePicture");
moshi.adapter((Type)(Class<Integer>)Integer.TYPE,·SetsKt.emptySet(),·"id");
moshi.adapter((Type)(Class<Boolean>)Boolean.TYPE,·SetsKt.emptySet(),·"personalizedMarketingConsent");
```

Decompiled code generated with ir
```
moshi.adapter(TypesJVMKt.getJavaType(Reflection.typeOf((Class)String.class)),·SetsKt.emptySet(),·"email");
moshi.adapter(TypesJVMKt.getJavaType(Reflection.typeOf((Class)ProfilePicture.class)),·SetsKt.emptySet(),·"profilePicture");
moshi.adapter(TypesJVMKt.getJavaType(Reflection.typeOf((Class)Integer.TYPE)),·SetsKt.emptySet(),·"id");
moshi.adapter(TypesJVMKt.getJavaType(Reflection.typeOf((Class)Boolean.TYPE)),·SetsKt.emptySet(),·"personalizedMarketingConsent");
```

The full comparison of 2 classes.jar files: https://try.diffoscope.org/aeurvkfzuebe.html

**Comment by ZacSweers** [comment]
I think the simplest solution would probably just be to directly inline the class calls. It's convenient to be able to use typeOf() but IR might be too late to do so
