### ISSUE TITLE
Can't serialize @DefaultObject?

### ISSUE THREAD

**Issue by ursusursus** [ZacSweers/MoshiX#208]
Hi,

```kotlin
@JsonClass(generateAdapter = true, generator = "sealed:type")
sealed class Code {
    abstract val id: String
    abstract val validFromTimestamp: Long
    abstract val validToTimestamp: Long?

    @TypeLabel("qr")
    @JsonClass(generateAdapter = true)
    data class QR(
        override val id: String,
        override val validFromTimestamp: Long,
        override val validToTimestamp: Long?,
        val value: String
    ) : Code()

    @TypeLabel("ean")
    @JsonClass(generateAdapter = true)
    data class EAN(
        override val id: String,
        override val validFromTimestamp: Long,
        override val validToTimestamp: Long?,
        val value: String
    ) : Code()

    @TypeLabel("text")
    @JsonClass(generateAdapter = true)
    data class Text(
        override val id: String,
        override val validFromTimestamp: Long,
        override val validToTimestamp: Long?,
        val value: String,
        val activatedViaSms: Boolean
    ) : Code()

    @TypeLabel("pic")
    @JsonClass(generateAdapter = true)
    data class Picture(
        override val id: String,
        override val validFromTimestamp: Long,
        override val validToTimestamp: Long?,
        val url: String
    ) : Code()

    @TypeLabel("base64_pic")
    @JsonClass(generateAdapter = true)
    data class Base64Picture(
        override val id: String,
        override val validFromTimestamp: Long,
        override val validToTimestamp: Long?,
        val value: String
    ) : Code()

    @DefaultObject
    object Invalid : Code() {
        override val id: String = ""
        override val validFromTimestamp: Long = 0
        override val validToTimestamp: Long = 0
    }
}
```

when parsing backend stuff & not match any type I return `Invalid`, then I try to serialize that to json to be saved to database.
However I get

```
2022-02-10 01:53:16.633 24580-24667/sk.o2.mojeo2.mock W/Default: Expected one of [class sk.o2.extra.data.model.ExtraOffer$Code$QR, class sk.o2.extra.data.model.ExtraOffer$Code$EAN, class sk.o2.extra.data.model.ExtraOffer$Code$Text, class sk.o2.extra.data.model.ExtraOffer$Code$Picture, class sk.o2.extra.data.model.ExtraOffer$Code$Base64Picture] but found sk.o2.extra.data.model.ExtraOffer$Code$Invalid@c99a82c, a class sk.o2.extra.data.model.ExtraOffer$Code$Invalid. Register this subtype.
    java.lang.IllegalArgumentException: Expected one of [class sk.o2.extra.data.model.ExtraOffer$Code$QR, class sk.o2.extra.data.model.ExtraOffer$Code$EAN, class sk.o2.extra.data.model.ExtraOffer$Code$Text, class sk.o2.extra.data.model.ExtraOffer$Code$Picture, class sk.o2.extra.data.model.ExtraOffer$Code$Base64Picture] but found sk.o2.extra.data.model.ExtraOffer$Code$Invalid@c99a82c, a class sk.o2.extra.data.model.ExtraOffer$Code$Invalid. Register this subtype.
        at com.squareup.moshi.adapters.PolymorphicJsonAdapterFactory$1.toJson(PolymorphicJsonAdapterFactory.java:202)
        at com.squareup.moshi.adapters.PolymorphicJsonAdapterFactory$PolymorphicJsonAdapter.toJson(PolymorphicJsonAdapterFactory.java:320)
        at com.squareup.moshi.internal.NullSafeJsonAdapter.toJson(NullSafeJsonAdapter.java:50)
        at sk.o2.extra.data.model.ExtraOffer_CodeJsonAdapter.toJson(ExtraOffer_CodeJsonAdapter.kt:34)
        at sk.o2.extra.data.model.ExtraOffer_CodeJsonAdapter.toJson(ExtraOffer_CodeJsonAdapter.kt:13)
        at com.squareup.moshi.internal.NullSafeJsonAdapter.toJson(NullSafeJsonAdapter.java:50)
        at com.squareup.moshi.CollectionJsonAdapter.toJson(CollectionJsonAdapter.java:91)
        at com.squareup.moshi.CollectionJsonAdapter$2.toJson(CollectionJsonAdapter.java:55)
        at com.squareup.moshi.internal.NullSafeJsonAdapter.toJson(NullSafeJsonAdapter.java:50)
        at com.squareup.moshi.JsonAdapter.toJson(JsonAdapter.java:82)
        at com.squareup.moshi.JsonAdapter.toJson(JsonAdapter.java:90)
        at sk.o2.sqldelight.JsonColumnAdapter.encode(JsonColumnAdapter.kt:27)
```

So I'm confused. Can it only be used when deserializing, not serializing?

**Comment by ZacSweers** [comment]
Correct. This is how moshi's polymorphic adapter works. Defaults are solely for unrecognized keys. Intentionally serializing unknown objects is an error
