### ISSUE TITLE
Moshix sealed ksp incorrectly assumes single originating file with sealed subclasses defined in different files

### ISSUE THREAD

**Issue by efemoney** [ZacSweers/MoshiX#298]
Not sure if its intentional but I didn't read anything about this limitation in the docs

https://github.com/ZacSweers/MoshiX/blob/a6a7b4c5f863c3928fb3c764fc67fba0e63ad6ca/moshi-sealed/codegen/src/main/kotlin/dev/zacsweers/moshix/sealed/codegen/ksp/MoshiSealedSymbolProcessorProvider.kt#L278

**Stacktrace**
<details>

```
[ksp] java.lang.IllegalArgumentException: List has more than one element.
	at kotlin.collections.CollectionsKt___CollectionsKt.single(_Collections.kt:610)
	at dev.zacsweers.moshix.sealed.codegen.ksp.MoshiSealedSymbolProcessor.createType(MoshiSealedSymbolProcessorProvider.kt:278)
	at dev.zacsweers.moshix.sealed.codegen.ksp.MoshiSealedSymbolProcessor.process(MoshiSealedSymbolProcessorProvider.kt:190)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension$doAnalysis$4$1.invoke(KotlinSymbolProcessingExtension.kt:237)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension$doAnalysis$4$1.invoke(KotlinSymbolProcessingExtension.kt:235)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension.handleException(KotlinSymbolProcessingExtension.kt:330)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension.doAnalysis(KotlinSymbolProcessingExtension.kt:235)
...
```

<details>

**Comment by ZacSweers** [comment]
Strange, this should work. I'll look into it. Fwiw Moshi-ir does work for this case as we're using it at my job

**Comment by efemoney** [comment]
Yup I have switched to Moshi-ir! Also updated the title after debugging cos I think I understand the intention here. I can push a commit to fix it.
