### ISSUE TITLE
Stream closed in MGP while writing proguard files

### ISSUE THREAD

**Issue by ZacSweers** [ZacSweers/MoshiX#320]
Saw https://github.com/slackhq/circuit/runs/7796873708?check_suite_focus=true#step:7:194 today

```
e: java.io.IOException: Stream Closed
	at java.base/java.io.FileOutputStream.writeBytes(Native Method)
	at java.base/java.io.FileOutputStream.write(FileOutputStream.java:349)
	at java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:234)
	at java.base/sun.nio.cs.StreamEncoder.implClose(StreamEncoder.java:340)
	at java.base/sun.nio.cs.StreamEncoder.close(StreamEncoder.java:169)
	at java.base/java.io.OutputStreamWriter.close(OutputStreamWriter.java:252)
	at java.base/java.io.BufferedWriter.close(BufferedWriter.java:269)
	at kotlin.io.CloseableKt.closeFinally(Closeable.kt:57)
	at dev.zacsweers.moshix.ir.compiler.proguardgen.ProguardRuleGenerationExtension.doAnalysis(ProguardRuleGenerationExtension.kt:105)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration(TopDownAnalyzerFacadeForJVM.kt:123)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration$default(TopDownAnalyzerFacadeForJVM.kt:99)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:264)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:55)
	at org.jetbrains.kotlin.cli.common.messages.AnalyzerWithCompilerReport.analyzeAndReport(AnalyzerWithCompilerReport.kt:115)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.analyze(KotlinToJVMBytecodeCompiler.kt:255)
```

**Comment by ZacSweers** [comment]
Closing as I'm not sure what can be done about this tbh

**Comment by Dkhusainov** [comment]
I have the same issue after upgrading from 0.19.0 to 0.21.0 and kotlin 1.8. Any idea what causes this?

**Comment by Dkhusainov** [comment]
@ZacSweers I happens if you have one empty kotlin file with the same name as the json class 
![image](https://user-images.githubusercontent.com/7382654/229379051-e119c29e-f3e5-49e3-90d9-832062501d6c.png)
