### ISSUE TITLE
[Android] No JsonAdapter for NestedSealed interface if R8 enabled

### ISSUE THREAD

**Issue by proninyaroslav** [ZacSweers/MoshiX#324]
**Kotlin**: 1.7.10
**KSP**: 1.7.10-1.0.6
**Android libray**: 7.3.0-rc01
**Moshi**: 1.13.0
**moshi_sealed**: 1.7.20-Beta-0.18.3

I have this sealed interface in my Jetpack Compose app:

```Kotlin
@JsonClass(generateAdapter = true, generator = "sealed:type")
sealed interface PrefRecentCharactersFilter {
    @NestedSealed
    sealed interface DateAdded : PrefRecentCharactersFilter {
        @TypeLabel("date_added_unknown")
        object Unknown : DateAdded

        @TypeLabel("date_added_this_week")
        object ThisWeek : DateAdded

        @TypeLabel("date_added_in_range")
        @JsonClass(generateAdapter = true)
        data class InRange(val start: Date, val end: Date) : DateAdded
    }
}
```

And my Moshi builder looks like this:
```Kotlin
Moshi.Builder()
        .add(NestedSealed.Factory())
        .build()
```

I'm using a code gen for adapters. This works fine in a debug build, but if I build in a release with R8 enabled, the application throws an exception:

<details>
<summary>Log</summary>

```
FATAL EXCEPTION: main
Process: org.proninyaroslav.opencomicvine, PID: 27536
java.lang.IllegalArgumentException: No JsonAdapter for interface org.proninyaroslav.opencomicvine.data.preferences.PrefRecentCharactersFilter$DateAdded (with no annotations)
for interface org.proninyaroslav.opencomicvine.data.preferences.PrefRecentCharactersFilter$DateAdded dateAdded
for class org.proninyaroslav.opencomicvine.data.preferences.PrefRecentCharactersFilterBundle
 at com.squareup.moshi.Moshi$LookupChain.exceptionWithLookupStack(Moshi.java:88)
 at com.squareup.moshi.Moshi.adapter(Moshi.java:31)
 at org.proninyaroslav.opencomicvine.data.preferences.PrefRecentCharactersFilterBundleJsonAdapter.<init>(PrefRecentCharactersFilterBundleJsonAdapter.kt:25)
 at java.lang.reflect.Constructor.newInstance0(Native Method)
 at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
 at com.squareup.moshi.StandardJsonAdapters$1.create(StandardJsonAdapters.java:313)
 at com.squareup.moshi.Moshi.adapter(Moshi.java:25)
 at com.squareup.moshi.Moshi.adapter(Moshi.java:4)
 at org.proninyaroslav.opencomicvine.model.AppPreferencesImpl.getRecentCharactersFilters(AppPreferences.kt:5)
 at org.proninyaroslav.opencomicvine.model.paging.recent.CharactersRemoteMediator.fetch(CharactersRemoteMediator.kt:81)
 at org.proninyaroslav.opencomicvine.model.paging.ComicVineRemoteMediator.load$suspendImpl(ComicVineRemoteMediator.kt:776)
 at org.proninyaroslav.opencomicvine.model.paging.ComicVineRemoteMediator.load(Unknown Source:0)
 at androidx.paging.RemoteMediatorAccessImpl$launchRefresh$1$1.invokeSuspend(RemoteMediatorAccessor.kt:57)
 at androidx.paging.RemoteMediatorAccessImpl$launchRefresh$1$1.invoke(RemoteMediatorAccessor.kt:14)
 at androidx.paging.SingleRunner$runInIsolation$2.invokeSuspend(SingleRunner.kt:116)
 at androidx.paging.SingleRunner$runInIsolation$2.invoke(SingleRunner.kt:13)
 at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:5)
 at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:10)
 at androidx.paging.SingleRunner.runInIsolation(SingleRunner.kt:65)
 at androidx.paging.RemoteMediatorAccessImpl$launchRefresh$1.invokeSuspend(RemoteMediatorAccessor.kt:47)
 at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:9)
 at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:107)
 at kotlinx.coroutines.EventLoop.processUnconfinedEvent(EventLoop.common.kt:37)
 at kotlinx.coroutines.internal.DispatchedContinuation.resumeWith(DispatchedContinuation.kt:81)
 at kotlinx.coroutines.AbstractCoroutine.start$enumunboxing$(AbstractCoroutine.kt:77)
 at kotlinx.coroutines.flow.internal.ChannelFlow.produceImpl(ChannelFlow.kt:32)
 at kotlinx.coroutines.flow.internal.ChannelFlow$collect$2.invokeSuspend(ChannelFlow.kt:33)
 at kotlinx.coroutines.flow.internal.ChannelFlow$collect$2.invoke(ChannelFlow.kt:13)
 at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:5)
 at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:10)
 at kotlinx.coroutines.flow.internal.ChannelFlow.collect(ChannelFlow.kt:7)
 at kotlinx.coroutines.flow.internal.ChannelFlowOperator.collect(ChannelFlow.kt:98)
 at kotlinx.coroutines.flow.FlowKt__EmittersKt$onStart$$inlined$unsafeFlow$1.collect(SafeCollector.common.kt:110)
 at kotlinx.coroutines.flow.FlowKt__EmittersKt$onStart$$inlined$unsafeFlow$1$1.invokeSuspend(Unknown Source:12)
 at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:9)
 at kotlinx.coroutines.flow.internal.SafeCollector.invokeSuspend(SafeCollector.kt:22)
 at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:9)
 at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:107)
 at android.os.Handler.handleCallback(Handler.java:883)
 at android.os.Handler.dispatchMessage(Handler.java:100)
 at android.os.Looper.loop(Looper.java:214)
 at android.app.ActivityThread.main(ActivityThread.java:7356)
```

</details>

**Comment by proninyaroslav** [comment]
Important clarification: an exception occurs if I specify a nested sealed interface as a property type in another date class that I also serialize, for example:
```Kotlin
@JsonClass(generateAdapter = true)
data class PrefRecentCharactersFilterBundle(
    val dateAdded: PrefRecentCharactersFilter.DateAdded,
)
```
here `PrefRecentCharactersFilter.DateAdded` is a nested interface. If I specify the property type as a `PrefRecentCharactersFilter`, then the exception doesn't occur.

@ZacSweers 
I wrote an example that exactly reproduces the problem in the release build (I used Android Studio Dolphin 2021.3.1 RC 1): https://github.com/proninyaroslav/moshi_sealed_R8_crash

**Comment by proninyaroslav** [comment]
@ZacSweers 
Have you looked at it?

**Comment by proninyaroslav** [comment]
It's still a critical problem, tested on `moshi` 1.14.0 and `ksp` 1.7.20-1.0.7. Because of this, I can't make a release build with minification.

**Comment by proninyaroslav** [comment]
Also tested on moshi_sealed `0.19.0`

**Comment by ZacSweers** [comment]
I am locking this issue for now because you are spamming it. It will be updated when I have a chance to look at it. I maintain this project in my free time, please be more respectful of maintainers' time as our urgency is not yours.

**Comment by ZacSweers** [comment]
Finally looking into this, the sample you linked is not buildable as-is and fails to even sync in the IDE

```
Build file '/Users/zacsweers/Downloads/moshi_sealed_R8_crash-master/app/build.gradle' line: 9

A problem occurred evaluating project ':app'.
> /Users/zacsweers/Downloads/moshi_sealed_R8_crash-master/key.properties (No such file or directory)
```

However I was able to work on this separately and figure out that this is a particular edge case where R8 is inlining the sealed parent _into_ the subtype. There's not an easy way to tell R8 to not do this without automatically keeping the entire class, but I did figure out a workaround that seems to do the trick by generating extra rules to keep the root adapter if the subtype itself is used
