### ISSUE TITLE
[KSP] No value found for value. Was null

### ISSUE THREAD

**Issue by chrisjenx** [ZacSweers/MoshiX#57]
Pretty sure this happens when there is a missing dependency on a module, not sure if it's possible yet, but would be good to surface the file/class that causes this?

```
e: java.lang.IllegalStateException: No value found for value. Was null
	at dev.zacsweers.moshix.ksp.MoshiApiUtilKt.generator(MoshiApiUtil.kt:138)
	at dev.zacsweers.moshix.ksp.JsonClassSymbolProcessor.adapterGenerator(JsonClassSymbolProcessor.kt:143)
	at dev.zacsweers.moshix.ksp.JsonClassSymbolProcessor.process(JsonClassSymbolProcessor.kt:95)
```

**Comment by chrisjenx** [comment]
Ahh this seems to happen when the file's package name does not math the file path. Seems like kapt masks these issues by stubbing.
Fix - make sure your file and package names match.

**Comment by chrisjenx** [comment]
Mmm, looks like a bug with KSP - I'll report over there.
